#!/usr/bin/env python3
"""GLSL source of the fast early-stage convolutions (3x3 or 1x1, bias, ReLU, 2x2 max pool).

The four early stages hold almost all of the network's multiply-adds. One invocation is one
pooled pixel and a block of output channels; lanes of a wave are neighbouring pixels, so every
weight is the same for the whole wave and is read through the scalar path, 16 words at a time.
Activations are FP16 pairs in vector registers; each product is a packed FP16 multiply and a
packed FP16 add on a pair of output channels, with the activation's half picked by the operand
swizzle. The two are kept apart (precise): the original run on a software renderer, and this
runtime on lavapipe, round the product to half before the add, and a fused multiply-add on the
console would round once. Fused, the console's output differed from the host's by 71 dB; apart,
the convolutions are the same bits on both. HELIXSR_CONV_FUSED=1 generates the fused form.

  acc[q][o/2] = bias;  for tap, input channel c:  acc[q][o/2] += a[q][c].hh * w[tap][c][o/2]   (q: the 2x2 cell's pixels)
  then ReLU, each pixel's plane of the unpooled tensor, and the maximum of the four for the pool.
The four pixels of a pooling cell are computed side by side, so a weight word is loaded once for four products.

Weights come in the runtime's "by input channel" order, made once at context creation:
half index ((tap_group * 8 + c % 8) * outputs + o), tap_group = ((c / 8) * K + ky) * K + kx,
so the outputs of one (tap, input channel) are adjacent. Tensors are NCHW8 as everywhere else.

Accumulation is FP16 in tap-group order: not the NVIDIA kernels' rounding sequence (the exact
kernels in shaders/convolution_pool_resident.hlsl keep that), the same choice as HelixSR's own."""

import os

VARIANTS = {
    # name: (input channels, output channels, kernel size, input is E5M3, output channels per invocation,
    #        byte offset of the weights in the network's weight blob)
    # 32 outputs per invocation: 16 accumulators, fed by one 16-word scalar load per input channel; the deep
    # layers have few pixels, and small blocks spread them over more waves.
    # The weight offsets are the planner's (third_party/helixsr/model, NCHW8 network; the runtime checks them).
    # They are literals because the compiler merges the scalar loads of a wave only from a constant base.
    "conv_16_32_k3_half": (16, 32, 3, False, 32, 0),
    "conv_32_64_k1_half": (32, 64, 1, False, 32, 9216),
    "conv_64_128_k3_e5": (64, 128, 3, True, 32, 13824),
    "conv_128_128_k3_half": (128, 128, 3, False, 32, 161536),
    "conv_128_256_k3_half": (128, 256, 3, False, 32, 456704),
}
LANES = 64
# A multiply and an add per product, each rounded to half, or (HELIXSR_CONV_FUSED=1) one fused multiply-add.
FUSED = os.environ.get("HELIXSR_CONV_FUSED", "0") == "1"


def source(name):
    cin, cout, k, e5, block, weight_offset = VARIANTS[name]
    pairs = block // 2
    taps = k * k
    lines = []
    emit = lines.append
    emit("#version 460")
    emit(f"// {name}: generated by tools/conv_kernels.py. Do not edit.")
    emit("#extension GL_EXT_shader_explicit_arithmetic_types : require")
    emit("#extension GL_EXT_control_flow_attributes : require")
    emit(f"layout(local_size_x = {LANES}) in;")
    emit("layout(set = 0, binding = 0) uniform Params {")
    emit("    uint width, height, input_offset, weight_offset, bias_offset, pool_offset, skip_offset, reserved;")
    emit("} params;")
    emit("layout(set = 0, binding = 1) readonly restrict buffer Activation { uint activation[]; };")
    emit("layout(set = 0, binding = 2) readonly restrict buffer Weights { uint weights[]; };")
    emit("layout(set = 0, binding = 3) writeonly buffer Pool { uint pool[]; };")
    emit("layout(set = 0, binding = 4) writeonly buffer Skip { uint skip[]; };")
    emit("void main() {")
    emit("    uint width = params.width, height = params.height, pw = width >> 1, ph = height >> 1;")
    emit(f"    uint pixel = gl_WorkGroupID.x * {LANES}u + gl_LocalInvocationID.x;")
    emit("    if (pixel >= pw * ph) return;")
    emit("    uint x = pixel % pw, y = pixel / pw;")
    emit(f"    uint first = gl_WorkGroupID.y * {block}u;   // this block's first output channel: the same for the whole wave")
    emit(f"    uint weight_base = {weight_offset // 4}u + (first >> 1);   // params.weight_offset, as a literal")
    emit("    uint bias_base = (params.bias_offset >> 2) + (first >> 1);")
    emit(f"    uint plane_words = {cout // 2}u * pw * ph;")
    emit(f"    uint out_cell = (((first >> 3) * ph + y) * pw + x) * 4u;")
    # the four pixels of the pooling cell run side by side: one weight word feeds four multiply-adds
    for p in range(pairs):
        emit(f"    {'' if FUSED else 'precise '}f16vec2 s0_{p} = unpackFloat2x16(weights[bias_base + {p}u]), s1_{p} = s0_{p}, s2_{p} = s0_{p}, s3_{p} = s0_{p};")
    emit(f"    [[dont_unroll]] for (uint t = 0u; t < {taps * cin // 8}u; ++t) {{")
    if k == 1:
        emit("        uint group = t; int dx = 0, dy = 0;")
    else:
        emit(f"        uint group = t / {taps}u, tap = t % {taps}u;")
        emit(f"        int dx = int(tap % {k}u) - {k // 2}, dy = int(tap / {k}u) - {k // 2};")
    for q in range(4):
        emit(f"        int sx{q} = int(2u * x) + {q & 1} + dx, sy{q} = int(2u * y) + {q >> 1} + dy;")
        emit(f"        bool in{q} = sx{q} >= 0 && sy{q} >= 0 && sx{q} < int(width) && sy{q} < int(height);")
        emit(f"        uint c{q} = (group * height + uint(clamp(sy{q}, 0, int(height) - 1))) * width + uint(clamp(sx{q}, 0, int(width) - 1));")
        if e5:
            # E5M3: a half is the byte shifted left by 7
            emit(f"        uint at{q} = (params.input_offset >> 2) + c{q} * 2u;")
            emit(f"        uint lo{q} = in{q} ? activation[at{q}] : 0u, hi{q} = in{q} ? activation[at{q} + 1u] : 0u;")
            for d, word in enumerate((f"lo{q}", f"lo{q}", f"hi{q}", f"hi{q}")):
                if d % 2 == 0:
                    emit(f"        f16vec2 a{q}_{d} = unpackFloat2x16((({word} & 0xffu) << 7) | (({word} & 0xff00u) << 15));")
                else:
                    emit(f"        f16vec2 a{q}_{d} = unpackFloat2x16((({word} >> 9) & 0x7f80u) | (({word} >> 1) & 0x7f800000u));")
        else:
            emit(f"        uint at{q} = (params.input_offset >> 2) + c{q} * 4u;")
            for d in range(4):
                emit(f"        f16vec2 a{q}_{d} = unpackFloat2x16(in{q} ? activation[at{q} + {d}u] : 0u);")
    emit(f"        uint w = weight_base + t * {8 * cout // 2}u;")
    for i in range(8):
        half = 'xx' if i % 2 == 0 else 'yy'
        for p in range(pairs):
            emit(f"        {{ f16vec2 v = unpackFloat2x16(weights[w + {i * cout // 2 + p}u]); " +
                 " ".join(f"s{q}_{p} = fma(a{q}_{i // 2}.{half}, v, s{q}_{p});" if FUSED else
                          f"s{q}_{p} = s{q}_{p} + a{q}_{i // 2}.{half} * v;" for q in range(4)) + " }")
    emit("    }")
    emit("    uint plane = (params.skip_offset >> 2) + out_cell, cell = (params.pool_offset >> 2) + out_cell;")
    for p in range(pairs):
        # NCHW8: group j of the block starts (j * ph * pw * 4) words further on
        offset = f"{p // 4}u * ph * pw * 4u + {p % 4}u"
        for q in range(4):
            emit(f"    s{q}_{p} = max(s{q}_{p}, f16vec2(0.0hf)); skip[plane + {q}u * plane_words + {offset}] = packFloat2x16(s{q}_{p});")
        emit(f"    pool[cell + {offset}] = packFloat2x16(max(max(s0_{p}, s1_{p}), max(s2_{p}, s3_{p})));")
    emit("}")
    return "\n".join(lines) + "\n"


def grid(name, width, height):
    """Dispatch size for an input of width x height."""
    _, cout, _, _, block, _ = VARIANTS[name]
    return [((width // 2) * (height // 2) + LANES - 1) // LANES, cout // block, 1]


if __name__ == "__main__":
    import sys
    sys.stdout.write(source(sys.argv[1]))
